spring.application.name=taskapp
server.servlet.context-path=/taskapp

#DB Config (use ENV variables in test)
server.port=9091  
spring.datasource.url=jdbc:mariadb://localhost:3306/taskappdb
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
paths=http://localhost:4500/
file_maillog=D:/Spring_Workspace/hdapp_api/hdapp_api/maillog
client_file_path=D:/Spring_Workspace/hdapp_api/hdapp_api/uploads
company_logo=D:/Spring_Workspace/hdapp_api/hdapp_api/uploads/
pdffilepath=D:/Spring_Workspace/dupak_api/dupak_api/src/main/resources/templates/
pdfsavepath=D:/Angular project/dupakcrm/src/assets/uploads/pdfpath/
file_path=D:/Angular project/dupakcrm/src/assets/uploads/Purchase/
file_path_quotation=D:/Angular project/dupakcrm/src/assets/uploads/quotation/
task.upload-dir=C:/Users/wesld/OneDrive/Desktop/frontend/240826/taskapp/src/assets/uploads/task/



#DB Config (use ENV variables in Live)
#server.port=8080  
#spring.datasource.url=jdbc:mariadb://localhost:3306/taskappdb?characterSetResults=UTF-8&characterEncoding=UTF-8&useUnicode=yes&autoReconnect=true
#spring.datasource.username=taskappdbuser
#spring.datasource.password=HAs3Spehe5RWrat
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#paths=https://app.webelement.cc/dupakcrm/
#file_maillog=/opt/content/dupakcrm/maillog
#client_file_path=/opt/content/dupakcrm/uploads
#company_logo=/opt/content/dupakcrm/uploads/
#pdffilepath=/opt/content/dupakcrm/uploads/templates/
#pdfsavepath=/opt/content/dupakcrm/uploads/pdfpath/
#file_path=/opt/content/dupakcrm/uploads/Purchase/
#file_path_quotation=/opt/content/dupakcrm/uploads/quotation/
#task.upload-dir=/opt/content/taskapp/uploads/tasks

# Connection Pool (HikariCP)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

# Hibernate / JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true 
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# JWT 120000 ms = 120 seconds = 2 minutes 1200000 20min
#jwt.expiration=1200000  
jwt.expiration=14400000
jwt.refreshExpiration=604800000
jwt.secret=k9A1r@3zD7vT#9LmXqB6N!gFz8WcP0Yd

# Custom properties
#ipflag=localIp
ipflag=localIp1
algorithm=DES
secret_key=PP@S@800


#liveurl ="https://app.webelement.cc/dupak/"

server.tomcat.connection-timeout=300000


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.enabled=true


