package com.webelement.taskapp.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import com.webelement.taskapp.dto.TaskDetailsDTO;
import com.webelement.taskapp.dto.TaskEditDTO;
import com.webelement.taskapp.dto.TaskRequestDTO;
import com.webelement.taskapp.entity.TaskEntity;
import com.webelement.taskapp.repo.TaskRepository;

@Service
public class TaskService {
	
	@Autowired
	private TaskRepository taskRepository;
	
	public Page<TaskDetailsDTO> findTaskDetails(
	        int page,
	        int size,
	        int statusIndex,
	        String search,
	        Integer clientId,

	        Integer taskCategoryId,

	        Integer assignedTo,

	        Integer priority) {

	    return taskRepository.findTaskDetails(
	            PageRequest.of(page, size),
	            statusIndex,
	            search,

	            clientId,

	            taskCategoryId,

	            assignedTo,

	            priority
	            
	            
	    );
	}

	 @Value("${task.upload-dir:uploads/tasks}")
	    private String uploadDir;


	 public TaskEntity saveTask(
		        Integer taskId,
		        Integer clientId,
		        LocalDate date,
		        Integer taskCategoryId,
		        String description,
		        Integer assignedTo,
		        Short priority,
		        String title,
		        Integer addedBy,
		        Short status,
		        MultipartFile pdfFile,
		        MultipartFile zipFile) throws Exception {

		    // =====================================================
		    // CREATE / UPDATE
		    // =====================================================

		    boolean isUpdate = taskId != null;

		    TaskEntity task;

		    if (isUpdate) {

		        task = taskRepository.findById(taskId)
		                .orElseThrow(() ->
		                        new RuntimeException("Task not found with id: " + taskId));

		    } else {

		        task = new TaskEntity();

		        // ID will be generated by database if AUTO_INCREMENT
		        task.setRegistrationDate(LocalDateTime.now());

		        // Default status for CREATE
		        task.setStatus((short) 1);

		        task.setAddedBy(addedBy);
		    }


		    // =====================================================
		    // COMMON FIELDS
		    // =====================================================

		    task.setTitle(title);

		    task.setClientId(clientId);

		    task.setDate(date);

		    task.setTaskCategoryId(taskCategoryId);

		    task.setDescription(description);

		    task.setAssignedTo(assignedTo);

		    task.setPriority(priority);


		    // =====================================================
		    // STATUS
		    // ONLY UPDATE
		    // =====================================================

		    if (isUpdate) {

		        if (status != null) {
		            task.setStatus(status);
		        }

		        task.setModificationDate(
		                LocalDateTime.now()
		        );
		    }


		    // =====================================================
		    // PDF FILE
		    // s_filename1
		    // =====================================================

		    if (pdfFile != null && !pdfFile.isEmpty()) {

		        validatePdf(pdfFile);

		        String fileName = saveFile(
		                pdfFile,
		                "pdf"
		        );

		        task.setFileName1(fileName);
		    }


		    // =====================================================
		    // ZIP FILE
		    // s_filename2
		    // =====================================================

		    if (zipFile != null && !zipFile.isEmpty()) {

		        validateZip(zipFile);

		        String fileName = saveFile(
		                zipFile,
		                "zip"
		        );

		        task.setFileName2(fileName);
		    }


		    // =====================================================
		    // SAVE
		    // =====================================================

		    return taskRepository.save(task);
		}


	    // =========================================================
	    // PDF VALIDATION
	    // =========================================================

	    private void validatePdf(MultipartFile file) {

	        String fileName = file.getOriginalFilename();

	        if (fileName == null ||
	                !fileName.toLowerCase().endsWith(".pdf")) {

	            throw new RuntimeException(
	                    "Only PDF files are allowed");
	        }

	        String contentType = file.getContentType();

	        if (contentType != null &&
	                !contentType.equalsIgnoreCase("application/pdf")) {

	            throw new RuntimeException(
	                    "Invalid PDF file");
	        }
	    }


	    // =========================================================
	    // ZIP VALIDATION
	    // =========================================================

	    private void validateZip(MultipartFile file) {

	        String fileName = file.getOriginalFilename();

	        if (fileName == null) {

	            throw new RuntimeException(
	                    "Invalid ZIP file");
	        }

	        String lowerName =
	                fileName.toLowerCase();

	        if (!lowerName.endsWith(".zip")) {

	            throw new RuntimeException(
	                    "Only ZIP files are allowed");
	        }
	    }


	    // =========================================================
	    // SAVE FILE
	    // =========================================================

	    private String saveFile(
	            MultipartFile file,
	            String type) throws IOException {

	        Path directory =
	                Paths.get(uploadDir, type);

	        Files.createDirectories(directory);


	        String originalName =
	                file.getOriginalFilename();

	        String extension = "";

	        if (originalName != null) {

	            int index =
	                    originalName.lastIndexOf(".");

	            if (index >= 0) {
	                extension =
	                        originalName.substring(index);
	            }
	        }


	        String newFileName =
	                UUID.randomUUID()
	                        .toString()
	                        + extension;


	        Path target =
	                directory.resolve(newFileName);


	        Files.copy(
	                file.getInputStream(),
	                target,
	                StandardCopyOption.REPLACE_EXISTING
	        );


	        return newFileName;
	    }
	    
	    public TaskEditDTO getTaskById(Integer taskId) {

	        return taskRepository
	                .findTaskById(taskId)
	                .orElseThrow(
	                    () -> new RuntimeException(
	                        "Task not found with ID: " + taskId
	                    )
	                );
	    }

}
