package com.webelement.taskapp.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;

import com.webelement.taskapp.Exceptions.FileValidationException;
import com.webelement.taskapp.common.CommonFunction;
import com.webelement.taskapp.common.ResponseApi;
import com.webelement.taskapp.dto.ApiResponse;
import com.webelement.taskapp.dto.TaskDetailsDTO;
import com.webelement.taskapp.dto.TaskEditDTO;
import com.webelement.taskapp.dto.TaskRequestDTO;
import com.webelement.taskapp.dto.UpdateTaskStatusDTO;
import com.webelement.taskapp.entity.StateEntity;
import com.webelement.taskapp.entity.TaskEntity;
import com.webelement.taskapp.entity.TransactionEntity;
import com.webelement.taskapp.repo.StateRepo;
import com.webelement.taskapp.repo.TaskRepository;

import lombok.RequiredArgsConstructor;

@Service
@RequiredArgsConstructor
public class TaskService {

	@Autowired
	private TaskRepository taskRepository;
	private final CommonFunction commonFunction;
	private final HttpServletRequest httpRequest;
	private static final long MAX_PDF_SIZE = 10 * 1024 * 1024; // 10 MB
	private static final long MAX_ZIP_SIZE = 50 * 1024 * 1024; // 50 MB
	private static final Map<Short, Short> STATUS_FLOW = Map.of((short) 1, (short) 2,(short) 2, (short) 3,(short) 3, (short) 4,(short) 4, (short) 5);


	@Value("${task.upload-dir}")
	private String uploadDir;


	public Page<TaskDetailsDTO> findTaskDetails(int page, int size, int statusIndex, String search, Integer clientId,
			Integer taskCategoryId,
			Integer assignedTo,
			Integer priority, String fromDate, String toDate,String isAdmin,Integer userId,Integer taskStatusId) {
		
		
	
	    return taskRepository.findTaskDetails(
	            PageRequest.of(page, size),
	            statusIndex,
	            search,

	            clientId,

	            taskCategoryId,

	            assignedTo,

	            priority,
	            fromDate,toDate,
	            isAdmin,
	            userId,
	            taskStatusId
	            
	            
	    );

	}

	@Transactional
	public TaskEntity saveTask(Integer taskId, Integer clientId, LocalDate date, Integer taskCategoryId,
			String description, Integer assignedTo, Short priority, String title, Integer addedBy, Short status,
			MultipartFile pdfFile, MultipartFile zipFile) throws Exception {

		// =====================================================
		// CREATE / UPDATE
		// =====================================================

		boolean isUpdate = taskId != null;

		TaskEntity task;

		if (isUpdate) {

			task = taskRepository.findById(taskId)
					.orElseThrow(() -> new RuntimeException("Task not found with id: " + taskId));

		} else {
			task = new TaskEntity();
			// ID will be generated by database if AUTO_INCREMENT
			task.setRegistrationDate(LocalDateTime.now());
			// Default status for CREATE
			task.setStatus((short) 1);
			task.setAddedBy(addedBy);
			task.setTaskStatus((short) 1);
		}
		task.setTitle(title);
		task.setClientId(clientId);
		task.setDate(date);
		task.setTaskCategoryId(taskCategoryId);
		task.setDescription(description);
		task.setAssignedTo(assignedTo);
		task.setPriority(priority);
		if (isUpdate) {
			if (status != null) {
				task.setStatus(status);
			}
			task.setModificationDate(LocalDateTime.now());
		}
		if (pdfFile != null && !pdfFile.isEmpty()) {
			validatePdf(pdfFile);
			String fileName = saveFile(pdfFile, "pdf");
			task.setFileName1(fileName);
		}
		if (zipFile != null && !zipFile.isEmpty()) {
			validateZip(zipFile);
			String fileName = saveFile(zipFile, "zip");
			task.setFileName2(fileName);
		}
		TaskEntity savedTask = taskRepository.save(task);
		String action = isUpdate ? "Task Updated" : "Task Added";
		commonFunction.createHistoryAccess(addedBy, commonFunction.resolveClientIp(httpRequest),
				commonFunction.getLocalIp(), action, 10, savedTask.getTaskId(), -1);
		return savedTask;
	}

	private void validatePdf(MultipartFile file) throws IOException {
		String contentType = file.getContentType();

		if (!"application/pdf".equalsIgnoreCase(contentType)) {
			throw new FileValidationException("Invalid PDF file");
		}

		byte[] header = new byte[4];
		file.getInputStream().read(header);

		String magic = new String(header);
		if (!magic.startsWith("%PDF")) {
			throw new FileValidationException("Corrupted PDF file");
		}
	}

	private void validateZip(MultipartFile file) throws IOException {

		byte[] header = new byte[4];
		file.getInputStream().read(header);

		if (header[0] != 'P' || header[1] != 'K') {
			throw new FileValidationException("Invalid ZIP file");
		}
	}

	// =========================================================
	// SAVE FILE
	// =========================================================

	private String saveFile(MultipartFile file, String type) throws IOException {

		Path directory = Paths.get(uploadDir, type);

		Files.createDirectories(directory);

		String originalName = file.getOriginalFilename();

		String extension = "";

		if (originalName != null) {

			int index = originalName.lastIndexOf(".");

			if (index >= 0) {
				extension = originalName.substring(index);
			}
		}

		String newFileName = UUID.randomUUID().toString() + extension;

		Path target = directory.resolve(newFileName);

		Files.copy(file.getInputStream(), target, StandardCopyOption.REPLACE_EXISTING);

		return newFileName;
	}

	public TaskEditDTO getTaskById(Integer taskId) {
		List<TransactionEntity> history = commonFunction.getTransactionLogs(10, taskId);
		TaskEditDTO taskDto = taskRepository.findTaskById(taskId)
				.orElseThrow(() -> new RuntimeException("Task not found with ID: " + taskId));
		taskDto.setTransactionHistory(history);
		return taskDto;
	}

	public ResponseEntity<ResponseApi<String>> deleteTask(int taskId, int createdBy, HttpServletRequest httpRequest) {

		 
		
		Optional<TaskEntity> existingTask = taskRepository.findById(taskId);

		if (!existingTask.isPresent()) {

			return ResponseEntity.status(HttpStatus.NOT_FOUND).body(new ResponseApi<>(false, "Task not found", null));
		}
		// 3 = Deleted
		int updatedRows = taskRepository.deleteTask((short) 3, taskId);
		if (updatedRows > 0) {
			commonFunction.createHistoryAccess(createdBy, commonFunction.resolveClientIp(httpRequest),
					commonFunction.getLocalIp(), "Task Deleted", 1, taskId, -1);
			return ResponseEntity.ok(new ResponseApi<>(true, "Task deleted successfully", null));
		} else {
			return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
					.body(new ResponseApi<>(false, "Failed to delete task", null));
		}
	}

	@Transactional
	public TaskEntity updateTaskStatus(UpdateTaskStatusDTO dto) throws Exception {

		TaskEntity task = taskRepository.findById(dto.getTaskId())
				.orElseThrow(() -> new RuntimeException("Task not found"));

		System.err.print(dto.getSelectedTaskStatusId());

		Short currentStatus = task.getTaskStatus();
		Short nextStatus;
		// Status 2 has two choices
		if (currentStatus == 2) {
			Map<Short, Short> status2Flow = Map.of((short) 3, (short) 3, // Re-Open
					(short) 5, (short) 5 // Assignor Closure
			);

			Short selectedStatus = Short.valueOf(dto.getSelectedTaskStatusId());
			nextStatus = status2Flow.get(selectedStatus);

			System.err.println("{next status }" + nextStatus);

			if (nextStatus == null) {
				throw new RuntimeException("Please select a valid task status.");
			}

		} else {
			// Normal flow
			nextStatus = STATUS_FLOW.get(currentStatus);

			if (nextStatus == null) {

				if (currentStatus == 5) {
					throw new RuntimeException("This task is already closed and cannot be updated.");
				}

				throw new RuntimeException("Invalid task status: " + currentStatus);
			}
		}

		task.setTaskStatus(nextStatus);
		task.setDescription(dto.getDescription());
		task.setModificationDate(LocalDateTime.now());

		// PDF Upload
		if (dto.getFileName1() != null && !dto.getFileName1().isEmpty()) {

			validatePdf(dto.getFileName1());

			String pdfFileName = saveFile(dto.getFileName1(), "pdf");

			task.setFileName1(pdfFileName);
		}

		// ZIP Upload
		if (dto.getFileName2() != null && !dto.getFileName2().isEmpty()) {

			validateZip(dto.getFileName2());

			String zipFileName = saveFile(dto.getFileName2(), "zip");

			task.setFileName2(zipFileName);
		}

		TaskEntity savedTask = taskRepository.save(task);

		commonFunction.createHistoryAccess(task.getAddedBy(), commonFunction.resolveClientIp(httpRequest),
				commonFunction.getLocalIp(), "Task Status Updated", 10, savedTask.getTaskId(), -1);

		return savedTask;
	}
}
